/*
connect-api

# API Rules * Null values are not sent / received. * Object IDs are **always** sent in list methods, but are **ignored** in create / update methods. * All request and response objects are at the root of the returned structure, if they contain only one entity. * Response of multiple entities is returned as an object that contains the list of entities and a structure `pager`, if necessary. ### Additional documentation: * [Camera registration](../camera_registration/) * [Camera communication](../camera_communication/) ### HTTP Status * 200 - OK, response contains data (usually the entire entity) * 201 - OK, entry created; response contains data as required * 204 - OK, no response * 304 - Response has not been modified * 400 - Invalid request / invalid input (SDK error) * 401 - Endpoint is being accessed without credentials (SDK error) * 403 - Request can't be served, usually due to insufficient rights (user error) * 404 - Entity not found (user error or outdated data) * 409 - Conflict with the state of target resource (user error) * 50x - Server side error

API version: 0.22.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CameraOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CameraOptions{}

// CameraOptions Configuration of the camera
type CameraOptions struct {
	AvailableResolutions []CameraResolution `json:"available_resolutions,omitempty"`
}

// NewCameraOptions instantiates a new CameraOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCameraOptions() *CameraOptions {
	this := CameraOptions{}
	return &this
}

// NewCameraOptionsWithDefaults instantiates a new CameraOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCameraOptionsWithDefaults() *CameraOptions {
	this := CameraOptions{}
	return &this
}

// GetAvailableResolutions returns the AvailableResolutions field value if set, zero value otherwise.
func (o *CameraOptions) GetAvailableResolutions() []CameraResolution {
	if o == nil || IsNil(o.AvailableResolutions) {
		var ret []CameraResolution
		return ret
	}
	return o.AvailableResolutions
}

// GetAvailableResolutionsOk returns a tuple with the AvailableResolutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameraOptions) GetAvailableResolutionsOk() ([]CameraResolution, bool) {
	if o == nil || IsNil(o.AvailableResolutions) {
		return nil, false
	}
	return o.AvailableResolutions, true
}

// HasAvailableResolutions returns a boolean if a field has been set.
func (o *CameraOptions) HasAvailableResolutions() bool {
	if o != nil && !IsNil(o.AvailableResolutions) {
		return true
	}

	return false
}

// SetAvailableResolutions gets a reference to the given []CameraResolution and assigns it to the AvailableResolutions field.
func (o *CameraOptions) SetAvailableResolutions(v []CameraResolution) {
	o.AvailableResolutions = v
}

func (o CameraOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CameraOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvailableResolutions) {
		toSerialize["available_resolutions"] = o.AvailableResolutions
	}
	return toSerialize, nil
}

type NullableCameraOptions struct {
	value *CameraOptions
	isSet bool
}

func (v NullableCameraOptions) Get() *CameraOptions {
	return v.value
}

func (v *NullableCameraOptions) Set(val *CameraOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableCameraOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableCameraOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCameraOptions(val *CameraOptions) *NullableCameraOptions {
	return &NullableCameraOptions{value: val, isSet: true}
}

func (v NullableCameraOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCameraOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


